server {
    listen 80;

    # Dashboard estático
    location / {
        root  /usr/share/nginx/html;
        index index.html;
    }

    # API Python
    location /api/ {
        proxy_pass http://backend:5000;
    }

    # phpMyAdmin
    location /pma/ {
        proxy_pass http://phpmyadmin/;
        proxy_set_header Host $host;
    }

    # Dashboard EMQX
    location /emqx/ {
        proxy_pass http://emqx:18083/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
